### ISSUE TITLE
Issue with Installing

### ISSUE THREAD

**Issue by miketweaver** [maded2/plotng#1]
```
(venv) [root@chia ~]# go install plotng/cmd/plotng
go install: version is required when current directory is not in a module
        Try 'go install plotng/cmd/plotng@latest' to install the latest version
```

I'm not sure what I've done wrong, but this issue appears when following your instructions.

**Comment by maded2** [comment]
will look into it, maybe try the pre-built binaries for 64-bits Linux in the meantime.

**Comment by aj10017** [comment]
run `go get github.com/maded2/plotng`
then navigate to your main go folder and cd into `/pkg/mod/github.com/maded2/plotng@v0.0.0-20210425203059-5ec1e63a0867/cmd/plotng/`
run `go install`
it will prompt you to first install prerequisites using the `go get` command. install them and then run `go install` again. This seemed to fix the issues for me (at least on windows)

**Comment by maded2** [comment]
thanks, I will try to reproduce on another PC.

**Comment by CharlesWiltgen** [comment]
I wonder if it's related to this?

```go get: github.com/maded2/plotng@none updating to
	github.com/maded2/plotng@v0.0.0-20210426142913-255e664765eb: parsing go.mod:
	module declares its path as: plotng
	        but was required as: github.com/maded2/plotng
```
(I'm new to golang, apologies if this doesn't matter.)

**Comment by maded2** [comment]
Please use the pre-built binaries from the release.   I will change the README to reflect this suggestion.
