### ISSUE TITLE
StaggeringDelay doesn't work correctly on windows.

### ISSUE THREAD

**Issue by megablue** [maded2/plotng#11]
version 0.6, regardless of the value, it will always start the next plot in exactly 1 min (parallels plotting 2).

**Comment by maded2** [comment]
as per README.md, the staggering delays is applied when PlotNG process the TargetDirectory list and it wraps around to the beginning.   Also PlotNG will only create a new every minute no matter what.   Staggering delays between plots will be added soon.

**Comment by maded2** [comment]
delay per plot implemented
