### ISSUE TITLE
[Suggestion] Moves the completed plot to another (SSD) directory/drive as a buffer for mechanical hard drive before the final destination.

### ISSUE THREAD

**Issue by megablue** [maded2/plotng#12]
This is probably not the right place to implement such feature but I am going to make the suggestion anyway... 

when you move/copy a large file to mechanical drive, the write speed is going to be the bottleneck. however if copy the file to an SSD first, the disk space on the plotting drives can be freed sooner so that you can start the next plot sooner while maximizing the free space on the plotting drives. while this might sounds similar to -2 argument, it isn't exactly the same as it only deals with the finalized plot instead of involving with phase 3 and 4.

I think it will minimize time to start the next plot given the max active plots constraint.

**Comment by maded2** [comment]
you can set the target directory to be the 2nd SSD.  And have a separate script to copy the plots async to the final hard drive.  I personally do this already.
