### ISSUE TITLE
[FR] Make usage of Bitfield configurable

### ISSUE THREAD

**Issue by sistein** [maded2/plotng#14]
It would be great to have more possibilities regarding the actual plotting. 

One thing would be the possibility to disable bitfield if preferred.

**Comment by maded2** [comment]
implemented by @Lutwidse

**Comment by sistein** [comment]
Can you please check it is working?

I have added 

    "BitField": false,
    "DisableBitField": true,

but if I check using htop there is no "-e" in the process list. If I start a plot manually it is shown however...

**Comment by maded2** [comment]
hi, I've checked and it seem to work.  Please note the '-e' is at the end of the parameters list, so it may not show in htop as it may be truncated at the end of the screen. 

Also you only need this setting in the config.json

`"DisableBitField": true,`
