### ISSUE TITLE
Suggestion: show plot progress percentage in UI

### ISSUE THREAD

**Issue by tgroff** [maded2/plotng#16]
This chia-blockchain Wiki page shows a table estimate of progress percentages, could this information be used to display _percent/progress_ to the UI?

https://github.com/Chia-Network/chia-blockchain/wiki/Beginners-Guide#create-a-plot

Phase | Step | % Progress
-- | -- | --
1 | Computing table 1 | 1%
1 | Computing table 2 | 6%
1 | Computing table 3 | 12%
1 | Computing table 4 | 20%
1 | Computing table 5 | 28%
1 | Computing table 6 | 36%
1 | Computing table 7 | 42%
2 | Backpropagating on table 7 | 43%
2 | Backpropagating on table 6 | 48%
2 | Backpropagating on table 5 | 51%
2 | Backpropagating on table 4 | 55%
2 | Backpropagating on table 3 | 58%
2 | Backpropagating on table 2 | 61%
3 | Compressing tables 1 and 2 | 66%
3 | Compressing tables 2 and 3 | 73%
3 | Compressing tables 3 and 4 | 79%
3 | Compressing tables 4 and 5 | 85%
3 | Compressing tables 5 and 6 | 92%
3 | Compressing tables 6 and 7 | 98%
4 | Write checkpoint tables | 100%

Thanks for this great utility! 

--Tony

**Comment by maded2** [comment]
good idea,  will implement it asap

**Comment by maded2** [comment]
implemented
