### ISSUE TITLE
[FEATURES] stagger by phase

### ISSUE THREAD

**Issue by kaspar030** [maded2/plotng#19]
I'd like to be able to stagger the plots evenly or by phase. 

E.g., have only one plot running in phase 1 (which uses multiple threads).
Or, if I have 5 parallel plots, have them start at whenever the previous arrived at 100/5=20%.

Right now my plots are IO bound, so without manually increasing the number of parallel plots, they pretty much synchronize towards the end. At some point, I'm waiting for 5 plots to get copied at the same time over a slow network.

Thanks for this wonderful time saver!

**Comment by CharlesWiltgen** [comment]
That would be super-useful.

**Comment by maded2** [comment]
Have you try using

DelaysBetweenPlot option?

**Comment by kaspar030** [comment]
> Have you try using
> 
> DelaysBetweenPlot option?

yes, and I'm using that now, it works OK. But being able to specify "max N slots in phase 1" would be perfect, as that allows scheduling CPU threads (overcommitting them...). Right now I'm trying to do that manually, by setting DelaysBetweenPlot to a bit more than the average Phase 1 time.

**Comment by maded2** [comment]
I've merged a pull request for max plot for phase 1.  Will be in the next release
