### ISSUE TITLE
Support -f & -p

### ISSUE THREAD

**Issue by miketweaver** [maded2/plotng#2]
https://github.com/maded2/plotng/blob/5ec1e63a08671a24af513e8f9793a2bfff7b323c/internal/activePlot.go#L82

It would be nice if you supported `-f` & `-p` as an alternative to `-a`

This allows you to create plots without having the private keys on the plotter.

**Comment by s0ftice** [comment]
Thanks, this is a must-have for me too.
Currently I'm getting
   RuntimeError: No keys, please run 'chia keys add', 'chia keys generate' or provide a public key with -f
and I'm not keen to load private keys on untrusted plotters...

**Comment by maded2** [comment]
implemented
