### ISSUE TITLE
Only 8 parallel plots?

### ISSUE THREAD

**Issue by hunter6756** [maded2/plotng#21]
I'm plotting on Win10 with below settings, which are function normally with pure CLI.
As you can see I set the NumberOfParallelPlots to 12.
Before it running up to 8 parallel jobs it was great, but no more parallel job is created since then. 
I even waited until the the 1st job is completed, and the next 1st job is started, still there are only 8 parallel jobs.
Is this some windows only issue?

{
  "Fingerprint": "",
  "FarmerPublicKey": "*",
  "PoolPublicKey": "*",
  "Threads": 4,
  "Buffers": 4000,
  "NumberOfParallelPlots": 12,
  "TempDirectory": ["E:\\p", "F:\\p"],
  "TargetDirectory": ["D:\\p"],
  "StaggeringDelay": 2,
  "ShowPlotLog": true,
  "DiskSpaceCheck": true,
  "DelaysBetweenPlot": 20,
  "MaxActivePlotPerTarget": 0,
  "DisableBitField": false,
  "MaxActivePlotPerTemp": 6
}

**Comment by maded2** [comment]
I can't see anything wrong with the config file.  Can you do a screenshot of the UI for me to see.  thanks.

**Comment by maded2** [comment]
just saw you have "  "DiskSpaceCheck": true " in the config.  Do you target Directory have enough disk space? this option will stop starting new plots if there's not enough disk space on the target.

**Comment by hunter6756** [comment]
oh.. it doesn't, the target directory I set is a 1t SSD, and I'm using another scripts to move plots to my HDDs. I will set the DiskSpaceCheck to false.

Thanks. It's really a great tool.

**Comment by maded2** [comment]
thanks, will close this issue.
