### ISSUE TITLE
plotng not starting plots, suspecting stale server.targetDelayStartTime

### ISSUE THREAD

**Issue by kaspar030** [maded2/plotng#23]
I've been experimenting with different DelaysBetweenPlot  values, and suddenly, even when set to 0 or a low value, plotng wouldn't start a new plot.

I looked at the code, I suspect that when DelaysBetweenPlot was set to a high value, createNewPlot() would set server.targetDelayStartTime to that time in the future, in one of these lines:

https://github.com/maded2/plotng/blob/c8e4bb44186b7118d2335dac79ceeb604014cb04/internal/server.go#L76
or
https://github.com/maded2/plotng/blob/c8e4bb44186b7118d2335dac79ceeb604014cb04/internal/server.go#L97

If now a lower value is set, createNewPlot() will still always abort here:

https://github.com/maded2/plotng/blob/c8e4bb44186b7118d2335dac79ceeb604014cb04/internal/server.go#L70

... never taking into account a changed DelaysBetweenPlot. maybe server.targetDelayStartTime should be reset on config or value reload?

**Comment by maded2** [comment]
you are correct.  I will put in a fix

**Comment by maded2** [comment]
fixed.  the delay time is reset when new config is loaded
