### ISSUE TITLE
Windows Time

### ISSUE THREAD

**Issue by ninthwalker** [maded2/plotng#24]
First, thanks for this tool. Your client/server model was a great idea.

Issue: Time seems in seconds instead of minutes for Windows.
Expected behavior: "DelaysBetweenPlot": 90 # in 90 minutes it should kick off the next plot
Actual Behavior: Next plot starts in 90 seconds.

So it could either be a documentation change to let windows users know, or see what the fix might be for windows interpreting the time in seconds vs minutes.

**Comment by maded2** [comment]
can you try v0.15 as there was a bug in v0.14 to do with the delay settings.  Please report back.  thanks,

**Comment by maded2** [comment]
DelaysBetweenPlot is definitely in minutes.  Several other windows users reported this to be working.  Do you have the server log to show me?

**Comment by ninthwalker** [comment]
ok, so i checked again. It looks like it is fixed as you said in the latest 0.15. I thought I had ran that version but i gues I was still on the one prior. I did double check again and ran both the 0.15 and the old, and the old def started the plot right after the first as originally mentioned.

Thanks for replying quick, appreciate it.! You can close this one out.

**Comment by maded2** [comment]
thanks for the confirmation.
