### ISSUE TITLE
How to plot simultaneous staggers on multiple temp SSDs

### ISSUE THREAD

**Issue by VerstandInvictus** [maded2/plotng#29]
Currently it seems that DelaysBetweenPlot and StaggeringDelay are both global, that is to say, they apply across temp drives if more than one temp drive is set, not within a single temp drive.

What I'm trying to do, with 2 TempDirectory entries:
TempDirectory 1:
Max 4 parallel
2 max phase 1
delay 90 min between plots *on this drive*

TempDirectory 2 would be the same.

The result I'm looking for would be that every 90 minutes, PlotNG fires one plot on each drive, until MaxActivePlotPerPhase1 is met across both drives. After that, when 90 minutes has elapsed and a plot on either drive moves out of Phase 1, a new plot should fire on that drive.

What I'm seeing instead, with either StaggeringDelay or DelaysBetweenPlot, is 1 plot on TempDirectory 1, wait 90 min, 1 plot on TempDirectory2, wait 90 min, 1 plot on TempDirectory 1, wait 90 min... and so on.

Am I screwing up the config here, or is there not a way to do this currently?

**Comment by maded2** [comment]
In your complex use case, I would use 2 instances of plotng. Each instance manages one temp directory.  Just make sure you use a different port number for each instance

**Comment by VerstandInvictus** [comment]
I was thinking about doing that, yeah. That'll work, especially once the UI
can show multiple servers.

**Comment by ninthwalker** [comment]
I have been running multiple instances to do this type of thing as well

**Comment by maded2** [comment]
thanks @ninthwalker  for the confirmation.  If there's no other issue I will close this ticket tomorrow.
