### ISSUE TITLE
Feature request: Different config for each temp drive

### ISSUE THREAD

**Issue by joyarzun** [maded2/plotng#30]
Hello

I wondering whether we could have a different config for each drive because if you have a few drives with different speed maybe you want to have one fast drive with 3 parallel plots and a slow one with just 1 plot. I understand that plotng don't care about the drive's speed and you can't specify any config for that.

Have a good farming

**Comment by maded2** [comment]
I suggest you run multiple instance of plotng with individual configuration.   Then you can tailor each config per drive.   Please note you need to have different port number for each instance of plotng.

**Comment by joyarzun** [comment]
Oh I see. I'll test later with some time but this feature could be interesting to maintain the administration centralized. Well, not right now because official pools support it's right around the corner and that could change a lot of things.
Thanks for your comments

**Comment by maded2** [comment]
pooling will not change the way you manages your plotting.  I will be adding pooling support asap.
