### ISSUE TITLE
combined temp/temp2/target folders?

### ISSUE THREAD

**Issue by kaspar030** [maded2/plotng#31]
I'm plotting on hdds, which can each manage one simultaneous plot.
Currently, I'm running one plotng instance per hdd, because if I add each hdd as both temp folder and target folder, a plot might be split over two hdd, causing slowdown.
Unfortunately this doesn't allow plotng's awesome staggering/delaying to be applied?

Would it be possible to allow plotting to a single drive as both tmp and target, but having multiple of those?

**Comment by AmericanEnglish** [comment]
This seems to be the same as Issue #29  

The difference is that you want to keep the plot in the HDD the whole time.

The suggested solution in that same issue is to just run multiple instance of plotng. That would definitely fix your issue as well.

Simply run plotng with 2 config files. One where the temp and target is drive 1. Another where the temp and target is drive 2.

From there you can stagger them however you like through the different conf files.

**Comment by maded2** [comment]
hi, thanks for using my tool.   Can you share your config.  I do in fact something similar to your setup where the temp & target is the same drive.  I've 2 drives in this case.

This is my setup with staggering delays of 10mins.

```
{
  "Fingerprint": "",
  "NumberOfParallelPlots": 18,
  "TempDirectory": ["/media/eddie/plot1", "/media/eddie/plot2"],
  "TargetDirectory": ["/media/eddie/plot1", "/media/eddie/plot2"],
  "StaggeringDelay": 10
}
```

**Comment by kaspar030** [comment]
I've hit plotng mixing up temp and target drives. does it make a difference if the temp is a subdirectory? (I use "/tmp" for the temporaries.)

This is my config:

```
    1 {                                                                                                                                            
    2     "NumberOfParallelPlots": 3,                                                                                                              
    3     "TempDirectory": [                                                                                                                       
    4     "/chia/local/disk0/tmp",                                                                                                                 
    5     "/chia/local/disk1/tmp",                                                                                                                 
    6     "/chia/local/disk2/tmp"                                                                                                                  
    7     ],                                                                                                                                       
    8     "TargetDirectory": [                                                                                                                     
    9     "/chia/local/disk0",                                                                                                                     
   10     "/chia/local/disk1",                                                                                                                     
   11     "/chia/local/disk2"                                                                                                                      
   12     ],                                                                                                                                       
   13     "StaggeringDelay": 0,                                                                                                                    
   14     "DiskSpaceCheck": false,                                                                                                                 
   15     "DelaysBetweenPlot": 30,                                                                                                                 
   16     "MaxActivePlotPerTemp": 1,                                                                                                               
   17     "UseTargetForTmp2": true,                                                                                                                
   18 }                                                                                                                                            
```

**Comment by maded2** [comment]
the subdirs is fine.  As long as the path is unique then PlotNG is fine with it.  Not sure what do you mean by "mixing up temp and target drives"?

**Comment by kaspar030** [comment]
>  Not sure what do you mean by "mixing up temp and target drives"?

I'd expect to have one plot each building on a single drive. What happens is that sometimes, I get cross-device plots (with e.g., temp on disk1, target on disk). This happens after plotng has been running fine for a couple of days.

I have been adding folders while plotng was running, maybe that caused confusion. I'm pretty sure I did not add e.g., temp on disk0, target on disk1, in that order, so those would have been the next free tuple.
