### ISSUE TITLE
Feature request: abbreviate plot IDs to allow more useful info on narrow screens

### ISSUE THREAD

**Issue by VerstandInvictus** [maded2/plotng#33]
I run PlotNG UI on a portrait ultrawide monitor, and it'd be nice to be able to see the full stats in this scenario - right now, post multi-host-ui (which is wonderful BTW, thank you), my screen cuts off around the middle of "end time" in archived plots, preventing me from seeing durations of archived plots.

If the Plot ID, which is mostly irrelevant anyway, was visually truncated, say to 10 characters (which is more than enough to uniquely ID a plot using file search or whatever, in normal usage), I could almost definitely see everything at once on even this narrow screen.

**Comment by maded2** [comment]
good idea.  I will add it soon

**Comment by maded2** [comment]
implemented

**Comment by VerstandInvictus** [comment]
Beautiful, works perfect - thanks!

**Comment by squizzling** [comment]
@VerstandInvictus do you happen to know your terminal width (in characters)? I'm trying to get a feel for how much space is "spare" in each row.

**Comment by VerstandInvictus** [comment]
CMD in Windows will dynamically resize it, but it looks like on the portrait 1920x1080 monitor I usually leave it on, it's 134 characters.

When I want more width to see things like average plot times, I snap it to a half-ultrawide software display, which works out at 1720x1440. That puts it at 214 characters.
