### ISSUE TITLE
Bottleneck from Stage 4 Upload to Destination

### ISSUE THREAD

**Issue by jamesguan** [maded2/plotng#35]
Currently I'm running into an issue where my ethernet traffic is bottlenecked because all the plots are done but is uploading to a hard drive on the network all at once, causing the plots to not be available until all of them are copied over. It would be very useful to be able to limit stage 4 upload to one at a time. Would this be possible?

**Comment by maded2** [comment]
the only option is to stagger you plots so that they don't all finishes at the same time.  This is how must people are doing it.

**Comment by maded2** [comment]
any more updates, if not then I will close this ticket in 24hrs

**Comment by ayebear** [comment]
This issue can be solved by using plotng to output to a buffer drive, combined with a script like https://github.com/ayebear/automv to move the plot files to a network destination in the background, without blocking anything.
