### ISSUE TITLE
Open to implementation changes?

### ISSUE THREAD

**Issue by squizzling** [maded2/plotng#37]
In the process of making columns sortable, and adding a couple of other features I wanted, I've basically re-architected the entire UI.

Personally I think it's a cleaner design, but obviously I'm biased.  Would you be open to a set of PRs changing how a lot of the UI is managed?  Each panel can be updated in a self contained PR to keep them easier to review.

There's also a few changes around race conditions and security (specifically not listening on 0.0.0.0 by default).

**Comment by maded2** [comment]
I am totally happy to review and accept pull request.
