### ISSUE TITLE
Set a "MaxActivePlotPerTemp" limit for each Temp directory

### ISSUE THREAD

**Issue by belmond86** [maded2/plotng#38]
I use different NVME's (2 x 2TB and 1 x 1TB).
With PlotNG is it not possible to set a "MaxActivePlotPerTemp" for each Temp directory. The result is, that the 1TB NVME run out of space because PlotNG don't recognize that there is less space than an the other two NVME's.

Is it possible to fix that?

Thanks and Regards
Simon

**Comment by maded2** [comment]
The easiest solution is to create 2 subdir in each of your 2TB drives, hence we have now 5 x 1TB drives/path

NVME1/part1
NVME1/part2
NVME2/part1
NVME2/part2
NVME3

Now you know that all 5 drives/paths can be added as temp directory in the config.

happy plotting

**Comment by belmond86** [comment]
You are a genius bro, thank you so much. I was thinking a lot about how to solve that issue and the solution is so easy :)

**Comment by jackykwandesign** [comment]
i just want to ask this question , such a wonderful solution

**Comment by maded2** [comment]
If you like the tool, please give me a star 🌟 and maybe a small XCH donation
