### ISSUE TITLE
No GUI in windows just wall of text

### ISSUE THREAD

**Issue by Wontell** [maded2/plotng#39]
Hello,
Im plotting in windows and it looks like regualr plotting, wall of text, it looks Nothing like the screenshot posted  by the dev.

Am i doing something wrong?
I run it from CMD, should it be run from PowerShell?
![wall](https://user-images.githubusercontent.com/36778216/118411558-d5526680-b69d-11eb-9506-e71ef0576aa3.jpg)

Thanks

**Comment by Ramrawd** [comment]
Set ShowPlotLog to false in your config. Then run another cmd window with the following: plotng -ui -host <comma separated list of plotters host name or IP with/without port number>

**Comment by Wontell** [comment]
> Set ShowPlotLog to false in your config. Then run another cmd window with the following: plotng -ui -host <comma separated list of plotters host name or IP with/without port number>
> 
> So if you want to display it on the same computer, in another cmd window use: plotng -ui -host 127.0.0.1 -port 8484

Thanks, but in the LOG at the bottom it says no connection could be made becuase target machine activly refuses it

I tried doing same using my real  IP and port 8444, same result

**Comment by Wontell** [comment]
Yep can confirm 100% bug

When I start plotting with -port 8444
Then start GUI with -port 8444, it still trys to connect to 8484
So i run new ploting task with -port 8484
and then run the gui again and it worked, no more Refusing Connection

**Comment by maded2** [comment]
If you are using version v0 17+ then the UI command is now different to support multiple plotters

plotng -ui -host plotter1:port,plotter2:port

**Comment by Wontell** [comment]
> If you are using version v0 17+ then the UI command is now different to support multiple plotters
> 
> plotng -ui -host plotter1:port,plotter2:port

Thanks yep im on latest version.

Also for some reason your soft started to work when i copied it to same folder chia.exe was
I had GUI turned on for faming so it started the harvester, i manually checked via CLI to be sure.
But  your prog  errored out untill I copied it to and the config file to where the main chia.exe is.

**Comment by Wontell** [comment]
> If you are using version v0 17+ then the UI command is now different to support multiple plotters
> 
> plotng -ui -host plotter1:port,plotter2:port

Hi, I dont want to open a thread, so ill post here.
What does it mean "Orderly Shutdown"?
NumberOfParallelPlots : number of parallel plots to create. **Set to zero for orderly shutdown**

What will happen if I set it to 0? How many plots will it create in parallel and whats orderly shutdown?

**Comment by AmericanEnglish** [comment]
@Wontell If you set the plots to 0 it will not create any additional plots. It will continue to idle until you manually shutdown the server.

I think the idea is that when it is running and you need it to stop scheduling you should edit the config file and put parallel plots to 0. Then whenever you want to restart the plotting you just have to edit the config file to have greater than 0 parallel plots. plotng itself does not seem to exit of its own accord using this variable input.

**Comment by Wontell** [comment]
> @Wontell If you set the plots to 0 it will not create any additional plots. It will continue to idle until you manually shutdown the server.
> 
> I think the idea is that when it is running and you need it to stop scheduling you should edit the config file and put parallel plots to 0. Then whenever you want to restart the plotting you just have to edit the config file to have greater than 0 parallel plots. plotng itself does not seem to exit of its own accord using this variable input.

You mean if you need to do something, you set it to 0 and after it finishes running plots it wont start new ones?

BTW< can you upgrade the soft while plotting?

**Comment by AmericanEnglish** [comment]
Yes that is what I mean. If I have to work on the hardware of my plotter I set the parallel plots to 0, let them all finish, turn off the machine, the start everything back up.

Can you upgrade plotng while it is running? Probably but the new version of the executable will not automatically take over. You would have to kill the old running plotng and the gui. Then start the new executable and associated gui. This is a risky game to play.

Can you upgrade chia while it is running? Yes. Should you? No. If you update chia while plotng is running then when the next plot is queued the new chia plotting executable will be used. If the chia team decides to change the plotter behavior then you will end up with plotng using an executable it is no longer fit for. Note that the old plots will run to completion in any case bar any errors without issue (presumably).

**Comment by Wontell** [comment]
Thanks for the information.
I like this software its missing just 2 things, the automatic linear copy to HDD and SSD space optimization.
