### ISSUE TITLE
[Feature Request] Copy plot files from buffer SSD to HDD's one by one.

### ISSUE THREAD

**Issue by Wontell** [maded2/plotng#40]
Hello,
I would like to suggest a feature.

For the _plotng_ to copy created plots in orderly manner one by one to designated HDD or HDD's.

Right now many people use an SSD as "buffer" to speed up plotting [TargetDirectory], when plot files created they saved to this SSD [saves up to 20 minutes per p lot]
Also when bunch of parallel plots finish their jobs together and start copying to HDD [most people fill one HDD at time] it creates a bottleneck and slows the speed even more, but if you have an SSD, it doesnt really that big of a diffrence if its one file or 3 files copied to it, its still plenty fast.

Up till now I was manually copying the plot file from the "buffer" SSD to the HDD.

Also if its posible to RENAME the plot files while it copies, becuase the Chia Farming has a bug when you copy file it sees it as defective untill you restart the farming gui.
To solve this, i just rename .plot files to .pl before I copy, and when they copied i rename back to .plot.

**Comment by maded2** [comment]
I think everyone's requirements for copying to final destination is different.  Some users rsync/ftp/rclone the plots to other drive/hosts.  Some plot target is an external USB drives.   I personally uses different approach depending on the plotter in question.   So it is very unlikely I will add significant amount of effort add many possible destinations.  But I do welcome PR from you if you do implement something.

**Comment by AmericanEnglish** [comment]
If you are looking for something that can move plots from the target directory to a long term storage area then you may want to check out:
https://github.com/rjsears/chia_plot_manager

It specializes in this exact issue. The author notes that they use plotman for all plotting but these scripts for archival and transmission to long term storage.

I personally just have a bash script that runs in a permanent loop. It uses rsync to copy files from my staging drives to my long term storage. It works as well as anything else.

**Comment by ayebear** [comment]
This works very well for me combined with plotng outputting directly to a local buffer drive - https://github.com/ayebear/automv

**Comment by Wontell** [comment]
> I think everyone's requirements for copying to final destination is different. Some users rsync/ftp/rclone the plots to other drive/hosts. Some plot target is an external USB drives. I personally uses different approach depending on the plotter in question. So it is very unlikely I will add significant amount of effort add many possible destinations. But I do welcome PR from you if you do implement something.

This is mainly for windows users, its just a copy, you set a drive and it copies there .plot files one after another

**Comment by Wontell** [comment]
> This works very well for me combined with plotng outputting directly to a local buffer drive - https://github.com/ayebear/automv

Thanks but thats for linux

**Comment by ayebear** [comment]
> > This works very well for me combined with plotng outputting directly to a local buffer drive - https://github.com/ayebear/automv
> 
> Thanks but thats for linux

Ah, it might work with WSL, or on native windows if the `mv` commands are changed. I know someone who modified it to run successfully on windows.
