### ISSUE TITLE
TempDirectory concurrency limits

### ISSUE THREAD

**Issue by ayebear** [maded2/plotng#44]
Currently, it seems that plotng round-robins the specified temp directories for each new plot process. Since the temp directories might be on drives with different amounts of free space, this can lead to incorrect numbers of parallel plots per drive. One possible solution is to have a parallel array in the config:

```
...
"NumberOfParallelPlots": 10,
"TempDirectory": ["/mnt/2tb", "/mnt/1tb"],
"TempDirectoryLimits": [7, 3],
...
```

Or, re-structure the config similar to how [plotman](https://github.com/ericaltendorf/plotman/blob/main/src/plotman/resources/plotman.yaml#L40) allows specifying `tmp_overrides` options. I can help make these changes but want to make sure you like the design/config structure first.

Edit: MaxActivePlotPerTemp seems like a good start, but this still requires all the temp dirs to have the same free space.

**Comment by maded2** [comment]
My recommendation is to create subdirs in each drive to reflect on the number of plots you want for that drive.  Then set the MaxActivePlotPerTemp = 1.   In your example, I would do this.

Create sub directories
```
/mnt/2tb/1
/mnt/2tb/2
/mnt/2tb/3
/mnt/2tb/4
/mnt/2tb/5
/mnt/2tb/6
/mnt/2tb/7
/mnt/1tb/1
/mnt/1tb/2
/mnt/1tb/3
```
