### ISSUE TITLE
Strange Behavior, one Plot was pushed by more then hour

### ISSUE THREAD

**Issue by Wontell** [maded2/plotng#45]
This is my "Helper Plotter" its my main PC and it only plots when I use it to help the main one.

Here are my settings, it set to start all 4 plots with 5 minute delay, but as you can see from the screenshot, the last one was started with more then hour delay.

The I drive where the 3 plots run has 878GB of space, its more then enough for 3 plots that at max use 270gb of temp space
 [its two 1TB drives in RAID 0 with big overprovisioning so i reduced the size as much as posible]

  "Threads": 2,
  "Buffers": 0,
  "NumberOfParallelPlots": 4,
  "TempDirectory": ["D:/ChiaTemp", "I:/1", "I:/2", "I:/3"],
  "TargetDirectory": ["F:/Chia"],
  "StaggeringDelay": 0,
  "ShowPlotLog": false,
  "DiskSpaceCheck": true,
  "DelaysBetweenPlot": 5,
  "MaxActivePlotPerTarget": 0,
  "DisableBitField": false,
  "MaxActivePlotPerTemp": 1,
  "MaxActivePlotPerPhase1": 0,
  "UseTargetForTmp2": true,
  "BucketSize": 0

![1](https://user-images.githubusercontent.com/36778216/118561000-0d77a900-b773-11eb-9a79-f41eb1b4803d.jpg)

Any ideas?

Thanks

**Comment by maded2** [comment]
looking at the plot start time, it seems to me that you've changed the configuration more than once.  What you shown above may not be what you've been using.
From the configuration you shown above, the only thing that delay the last plot will be the **DiskSpaceCheck**, as it will not plot to the same target if there's not enough disk space to hold the final plots.

**Comment by Wontell** [comment]
> looking at the plot start time, it seems to me that you've changed the configuration more than once. What you shown above may not be what you've been using.
> From the configuration you shown above, the only thing that delay the last plot will be the **DiskSpaceCheck**, as it will not plot to the same target if there's not enough disk space to hold the final plots.


hmmm

In any case I disabled disk space check and tomorrow when i boot the PC ill test it again.

Thanks
