### ISSUE TITLE
[Feature Request] Please Let Us Use the Chia Queue Feature.

### ISSUE THREAD

**Issue by Wontell** [maded2/plotng#46]
Hi,
Please add a setting to the config file for the Chia queue system.
Reason: Me for example i start 7=8 parallel plots but each has a queue enabled
This way when plotting ends it starts a new one without killing chia.exe
And I can enable CPU affinity for each Chia.exe, i get each plot its 2 dedicated cores and it stays like this untill plotting ends.

Also it will allow to use the software at measured intervals, say you want to plot just 10 plots before you do soemthing with the PC, you can set a queue and it will end when all plots are done.

Thanks you

**Comment by maded2** [comment]
Not really sure what cpu affinity gives you, as only Phase 1 is multithreaded and IO bottleneck is the real issue to solve.   I don't intend to add -n option to PlotNG as it really goes against why I wrote it in the first place.

**Comment by Wontell** [comment]
> Not really sure what cpu affinity gives you, as only Phase 1 is multithreaded and IO bottleneck is the real issue to solve. I don't intend to add -n option to PlotNG as it really goes against why I wrote it in the first place.

I found that when you give each plotting task their own cores, it does help and saves 5-10 minutes and heats up the CPU less, i get lower temps, in the task manager all cores loaded equally.

When i started using plotNG i started to get less plots per 24 hours then before and trying to figure out why.

I was getting 34-36 plots per day and now im getting under 30 with plot NG

I would start 2 plotting tasks at same time one on optane and one on the RAID and then every 45 minutes it would start one more task for the raid, so in the end i have 7 plotting tasks one on Optane and 6 more on raid0
Also i used NVMe RAID0 as TEMP2 and target folder was SATA SSD



P.S. Can you consider adding an Ignore symbol for DelaysBetweenPlot to "TempDirectory".
For example if you want to start 3 plotting tasks at SAME TIME and then you want to start more tasks with delay.

It would be nice to add some symbol like say $ or # to Drive letter so it will ignore the DelaysBeetwenPlots and start a new plot immediately.

Something like this:

"TempDirectory": ["$C:/Chia_Temp", "$E:/1", "E:/2", "E:/3", "E:/4", "E:/5", "E:/6"],
"DelaysBetweenPlot": 45,

So it starts plotting on C:/Chia_Temp and E:/1 at same time while ignoring the DelaysBetweenPlot, and then all the rest will start based on DelaysBetweenPlot.

**Comment by Wontell** [comment]
Hi, since Queue is already implemented feature, for you it will be just to pass-trough the command, so people that want it, can use it, and it wont be like wasting time implementing a new feature, just enable existing one.
Well its your soft so whatever you decide goes.

**Comment by maded2** [comment]
PlotNG is designed to replace using the original chia plot create queue.  So I will not be adding this.  However, you are welcome to fork and add it to your own copy.
