### ISSUE TITLE
Plotng should pause/skip full drives

### ISSUE THREAD

**Issue by aj10017** [maded2/plotng#5]
Plotng should pause or skip devices that are running low on capacity. For example, a destination drive can continue to have plots prepared for it despite not enough free space existing on the drive to store the plots.

Perhaps plotng can calculate how many plots can be made for a destination drive when starting the plotting process, and then automatically stop that queue when the drive is full?

**Comment by maded2** [comment]
this is the next enhancement

**Comment by maded2** [comment]
done in v0.5
