### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ctahk0** [maded2/plotng#54]
I try it on ubuntu linux, and can't get it to work.
When start in gui mode, there is Log message: Get "http://localhost:8484/": dial tcp 127.0.0.1:8484 connect: connection refused.

With no gui there is only a message "Plotting exit with error: exit status 1"

**Comment by maded2** [comment]
basically, your plotng server is not running.   you need to check the config and make sure the plotng server is running without any error.  It will log to the screen and show you what's doing.

**Comment by maded2** [comment]
will close this issue.  If you still having issue, please re-open this issue.
