### ISSUE TITLE
can you add rsyng feature

### ISSUE THREAD

**Issue by cybertec2016** [maded2/plotng#57]
add rsyng feature to -d diskt to remote machine
https://github.com/ericaltendorf/plotman/wiki/Archiving

05-03 08:37:46 Starting archive: rsync --bwlimit=80000 --remove-source-files -P /mnt/dst1/plot-k32-2021-05-03-01-50-b4271f88a74b36b516c242151e00fdda20e3f31ce1f8624465bf05a195009ecd.plot rsync://username@plot.storage.ip:12000/chia/plots2

Copy the part after 05-03 08:37:46 Starting archive: . In our example that would be:
rsync --bwlimit=80000 --remove-source-files -P /mnt/plots1/plot-k32-2021-05-03-01-50-b4271f88a74b36b516c242151

**Comment by maded2** [comment]
I personally use runs rsync in a script to move plots.  Not sure if this should be part of PlotNG as Windows users will not be able to use it.

**Comment by squizzling** [comment]
You could do a generic "run after plot creation", with env vars for whatever. The rsync or robocopy.exe or whatever can be plugged in to that by users.
