### ISSUE TITLE
Plotting Exit with Error: exec: "chia": executable file not found in %PATH%

### ISSUE THREAD

**Issue by konkersgg** [maded2/plotng#61]
Im having this issue on Windows:

https://prnt.sc/13g2ev6

Ty!

**Comment by cybertec2016** [comment]
vc tem que adiciona ele na pasta onde esta adicionado o executavel da chia no teu caso e ~\AppData\Local\Chia-Blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\

**Comment by konkersgg** [comment]
> vc tem que adiciona ele na pasta onde esta adicionado o executavel da chia no teu caso e ~\AppData\Local\Chia-Blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\

Certo!

Seria melhor adicionar uma variável "Path" no arquivo config.json.

----------------

Would be better to add a "Path" variable to the config.json file.

**Comment by konkersgg** [comment]
It worked after moving it all to the chia.exe directory, but now I can't make it to save logs. I even added the SavePlotLogs option as i saw in some other issue thread.

`    "ShowPlotLog": false,
    "SavePlotLogs": true,
    "SavePlotLogDir": "C:/Users/KonkersGG/.chia/mainnet/plotter",`

This is on Windows 10 (gaming rig, wont be installing Linux).
