### ISSUE TITLE
Not saving logs? (Windows 10)

### ISSUE THREAD

**Issue by konkersgg** [maded2/plotng#64]
I can't make it to save logs. I even added the SavePlotLogs option as i saw in some other issue thread.

![image](https://user-images.githubusercontent.com/4704759/119750097-ee61d100-be6e-11eb-9067-153f0a82563c.png)

This is on Windows 10 (gaming rig, wont be installing Linux).

**Comment by maded2** [comment]
what does the PlotNG server log says,  any error messages?

**Comment by konkersgg** [comment]
> what does the PlotNG server log says, any error messages?

0.22

![image](https://user-images.githubusercontent.com/4704759/119922266-d9a43c80-bf45-11eb-9ca3-5560840997a5.png)

**Comment by konkersgg** [comment]
> what does the PlotNG server log says, any error messages?

Can't find a logfile, is there one? But on the server window it shows no error.

Today it is creating the logfiles though, lol.
