### ISSUE TITLE
Split client/server commands

### ISSUE THREAD

**Issue by squizzling** [maded2/plotng#67]
The specific drive is to split the command-line flags to make the addition of some cleaner.

Any objections to me doing this?

**Comment by maded2** [comment]
sorry, not sure what you mean.  Are you saying we have 2 separate commands?

**Comment by squizzling** [comment]
Yeah, plotng-server and plotng-client.

Right now there's 4 command line args (config, ui, host, and port).  Client uses host/ui, server uses config/port (and sort of ui in a negative fashion).  That makes things kinda messy.

**Comment by maded2** [comment]
good idea.
