### ISSUE TITLE
Extra plot when plotting?

### ISSUE THREAD

**Issue by CharlesWiltgen** [maded2/plotng#7]
I just started using `plotng`, and my config file sets `NumberOfParallelPlots` to 4 with a `StaggeringDelay` of 60.

A couple minutes after starting, I see two plotting operations happening. I'd expect one plot to start immediately, and the next to start in 60 minutes, etc. Am I misunderstanding how it should work?

This is on macOS in case it matters. Thank you!

**Comment by maded2** [comment]
The staggering is based on number of Destination directories.  eg.  If you have 2 destination directories and 4 parallel plots configured, then it will apply the staggering delays after started 2 plots.  It then waits for 60mins then start another 2 plots.   Hope this example makes it clearer.

**Comment by maded2** [comment]
thanks for confirming it works on MacOS.  I've also uploaded a pre-built binaries for Windows and MacOS for anyone else wanting to try.
