### ISSUE TITLE
GUI Mouse doesn't work in PuTTY

### ISSUE THREAD

**Issue by tariusagi** [maded2/plotng#77]
Mouse works perfectly in X terminal such as xfce4-terminal, but doesn't work in a PuTTY session. In  PuTTY, TERM set to "xterm", in xfce4-terminal, TERM set to xterm-256color.

**Comment by squizzling** [comment]
tcells mouse code can send modes 1000 (buttons), 1002 (buttons+drag), and 1003 (buttons+drag+motion, and what tview uses).  Out of these 3, putty only knows how to handle 1000 and 1002, so when it gets the request for 1003, it ignores it.

I can confirm that using either of the other two will work (at least on my system).  On Windows, the mode is ignored.  I don't know how macos handles the different options, although I suspect it will just work.

@maded2 - I can put through a PR which changes the mode, but unless you can test it on mac, it's probably best to put it behind a flag, like -alternate-mouse, or something.  Thoughts?

**Comment by maded2** [comment]
@squizzling thanks, let's do the PR with the option for MacOS.  Just amazing now that we have to cater for so many systems/setup.
