### ISSUE TITLE
MadMaxPlotter improvements

### ISSUE THREAD

**Issue by TheGoblinHero** [maded2/plotng#84]
TY for adding support for mmp!
1. MMP requires that paths ends with '/'. I think it's a good idea to automatically add '/' to the paths if the user didn't did it in the config.
2. Mmp works, but plotng-client shows empty log window.

**Comment by maded2** [comment]
1) will automatically add '/' to the end if the user didn't supply it
2) I can see log fine in the Log window (I am running on Ubuntu).  You do need to click on a specific plot.

**Comment by TheGoblinHero** [comment]
2. Oops. It shows if I click. But when there's an another room for improvement: fill the log window without clicking on plotng-client start. When I start it - Active plots window is active, first (and the only) plot is active, but log window is empty. Should be filled with the first plot log automatically.

**Comment by maded2** [comment]
1. will automatically add '/' to the end if the user didn't supply it

Done
