### ISSUE TITLE
MadMax Plotter Being Ignored on Windows

### ISSUE THREAD

**Issue by x86txt** [maded2/plotng#87]
If I use the following config on Windows, the madmax binary is not called and chia.exe is still executed to create plots. I am running the 0.24 release and using the following batch file to call plotng.exe:

@echo off
cd C:\Users\username\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon  
C:\Users\username\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon\plotng -config .\config.json

{
  "Fingerprint": "",  
  "FarmerPublicKey": "",  
  "PoolPublicKey": "",  
  "Threads": 3,  
  "Buffers": 8192,  
  "DisableBitField": false,  
  "NumberOfParallelPlots": 4,  
  "TempDirectory": ["E:/chia/tmp1", "C:/chia/tmp1", "E:/chia/tmp2", "C:/chia/tmp2"],  
  "TargetDirectory": ["U:/"],  
  "StaggeringDelay": 5,  
  "ShowPlotLog": false,  
  "DiskSpaceCheck": false,  
  "DelaysBetweenPlot": 0,  
  "MaxActivePlotPerTarget": 0,  
  "MaxActivePlotPerTemp": 1,  
  "MaxActivePlotPerPhase1": 0,  
  "UseTargetForTmp2": false,  
  "BucketSize": 64,  
  "SavePlotLogDir": "",  
  "PlotSize": 32,  
  "ChiaRoot": "",  
  "MadMaxPlotter": "C:/Users/username/AppData/Local/chia-blockchain/app-1.1.7/resources/app.asar.unpacked/daemon/chia_plot.exe"  
}

**Comment by maded2** [comment]
Don't think you are using the latest plotng.  As the command should

plotng-server -config config.json

**Comment by x86txt** [comment]
> Don't think you are using the latest plotng. As the command should
> 
> plotng-server -config config.json

Running plotng-server.exe fixed it, thanks Eddie.

The latest release has all 3 binaries: plotng.exe, plotng-server.exe, and plotng-client.exe. So I should ignore plotng.exe as deprecated?
