### ISSUE TITLE
Don't working with official 1.2.0 chia release

### ISSUE THREAD

**Issue by sanok2000** [maded2/plotng#91]
Get following ERROR

<img width="408" alt="Bildschirmfoto 2021-07-08 um 11 57 53" src="https://user-images.githubusercontent.com/61139856/124903197-08511080-dfe4-11eb-8dc6-5c2e0e7cc8b3.png">

I think, need ContractAddress here not PoolPublicKey

<img width="518" alt="Bildschirmfoto 2021-07-08 um 11 55 40" src="https://user-images.githubusercontent.com/61139856/124903414-3cc4cc80-dfe4-11eb-89be-b49e3a8b6139.png">

**Comment by maded2** [comment]
you are correct, just pushed a fix

**Comment by sanok2000** [comment]
Thanks
